build start check 2

diff --git a/my-app/Jenkinsfile b/my-app/Jenkinsfile
--- a/my-app/Jenkinsfile
+++ b/my-app/Jenkinsfile
@@ -66,17 +66,25 @@ pipeline {
                     sh '''
                     nohup npm start > app.log 2>&1 &
                     sleep 5
-                    curl -Is http://127.0.0.1:3000 || echo "App is not responding"
+                    cat app.log
+                    if ! curl -Is http://127.0.0.1:3000; then
+                        echo "App failed to start!"
+                        exit 1
+                    fi
                     '''
                     echo 'Starting ngrok for public access...'
                     sh '''
                     nohup ngrok http http://127.0.0.1:3000 --region=in --hostname=27a1-115-245-95-234.ngrok-free.app > ngrok.log 2>&1 &
                     sleep 5
-                    curl -Is https://d27f-106-51-157-202.ngrok-free.app || echo "Ngrok is not responding"
+                    if ! curl -Is https://d27f-106-51-157-202.ngrok-free.app; then
+                        echo "Ngrok is not responding!"
+                        exit 1
+                    fi
                     '''
                 }
             }
         }
+    }
     }
     post {
         success {
